title: wizard
description: Материалы канала vuutya
url: https://vchigrinsky.github.io
baseurl: /wizard
theme: jekyll-theme-primer
lang: ru
markdown: kramdown
exclude:
  - LOG.md
readme_index:
  with_frontmatter: true
