title: Компьютерный мастер Виктор
description: Компьютерный мастер Виктор — материалы
url: https://vchigrinsky.github.io
baseurl: /wizard
theme: jekyll-theme-primer
lang: ru
markdown: kramdown
exclude:
  - LOG.md
  - PUBLICATIONS.md
  - data/*.md
  - scripts/
  - vless.md
  - panels.md
  - direct.md
