#!/usr/bin/env bash
# Materialize Cloud Agent SSH_* (base64 private keys) + IP_* secrets into ~/.ssh.
# Expected pairs: SSH_BEGET_RU + IP_BEGET_RU → Host beget-ru
set -euo pipefail

SSH_DIR="${HOME}/.ssh"
mkdir -p "${SSH_DIR}"
chmod 700 "${SSH_DIR}"

CONFIG="${SSH_DIR}/config"
TMP_CONFIG="$(mktemp)"
trap 'rm -f "${TMP_CONFIG}"' EXIT

cat > "${TMP_CONFIG}" <<'EOF'
# Generated by .cursor/setup-ssh.sh — do not edit by hand.
Host *
  IdentitiesOnly yes
  StrictHostKeyChecking accept-new
  UserKnownHostsFile ~/.ssh/known_hosts
EOF

configured=0
skipped=0

while IFS= read -r ip_var; do
  [[ -z "${ip_var}" ]] && continue
  suffix="${ip_var#IP_}"
  ssh_var="SSH_${suffix}"

  ip_val="${!ip_var-}"
  key_b64="${!ssh_var-}"

  if [[ -z "${ip_val}" ]]; then
    echo "setup-ssh: skip ${suffix}: ${ip_var} empty"
    skipped=$((skipped + 1))
    continue
  fi
  if [[ -z "${key_b64}" ]]; then
    echo "setup-ssh: skip ${suffix}: ${ssh_var} missing or empty"
    skipped=$((skipped + 1))
    continue
  fi

  alias="$(echo "${suffix}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')"
  key_path="${SSH_DIR}/id_${alias}"

  if [[ "${key_b64}" == -----BEGIN* ]]; then
    printf '%s\n' "${key_b64}" > "${key_path}"
  else
    if ! printf '%s' "${key_b64}" | base64 -d > "${key_path}" 2>/dev/null; then
      echo "setup-ssh: skip ${suffix}: ${ssh_var} is not valid base64"
      rm -f "${key_path}"
      skipped=$((skipped + 1))
      continue
    fi
  fi

  if ! head -n1 "${key_path}" | grep -q 'BEGIN.*PRIVATE KEY'; then
    echo "setup-ssh: skip ${suffix}: decoded file is not an OpenSSH/PEM private key"
    rm -f "${key_path}"
    skipped=$((skipped + 1))
    continue
  fi

  chmod 600 "${key_path}"

  cat >> "${TMP_CONFIG}" <<EOF

Host ${alias}
  HostName ${ip_val}
  User root
  IdentityFile ${key_path}
EOF

  echo "setup-ssh: configured ${alias} → root@${ip_val}"
  configured=$((configured + 1))
done < <(env | awk -F= '/^IP_[A-Z0-9_]+=/{print $1}' | sort)

chmod 600 "${TMP_CONFIG}"
mv "${TMP_CONFIG}" "${CONFIG}"
trap - EXIT

echo "setup-ssh: done (configured=${configured}, skipped=${skipped})"
if [[ "${configured}" -eq 0 ]]; then
  echo "setup-ssh: no SSH hosts configured (need matching SSH_* + IP_* secrets)"
fi
